default: &default
  adapter: postgresql
  encoding: unicode
  user: admin
  password: qwerty123
  pool: 5

development:
  <<: *default
  database: rails-engli

test:
  <<: *default
  database: rails-engli

production:
  <<: *default
  database: rails-engli
  username: admin
  password: qwerty123
